---
name: Actualizar NGINX Ingress Controller

pipelineid: nginx-ingress

scms:
  default:
    kind: github
    spec:
      user: "{{ .github.user }}"
      email: "{{ .github.email }}"
      owner: "{{ .github.owner }}"
      repository: "{{ .github.repository }}"
      token: "{{ requiredEnv .github.token }}"
      username: "{{ .github.username }}"
      branch: "{{ .github.branch }}"

sources:
  chartLatestRelease:
    name: Última versión del chart
    kind: helmchart
    spec:
      url: https://kubernetes.github.io/ingress-nginx
      name: ingress-nginx

  imageLatestRelease:
    name: Última versión de la imagen
    kind: dockerimage
    spec:
      image: registry.k8s.io/ingress-nginx/controller
      tagfilter: "^v[0-9]+\\.[0-9]+\\.[0-9]+$"

targets:
  updateChartVersion:
    name: Actualizar versión del chart
    kind: file
    sourceid: chartLatestRelease
    scmid: default
    spec:
      file: applications/ingress-nginx/deploy.sh
      matchpattern: "CHART_VERSION=.*"
      replacepattern: CHART_VERSION={{ source "chartLatestRelease" }}

  updateImageTag:
    name: Actualizar tag de imagen
    kind: yaml
    sourceid: imageLatestRelease
    scmid: default
    spec:
      file: applications/ingress-nginx/values.yaml
      key: "$.controller.image.tag"
      value: "{{ source \"imageLatestRelease\" }}"

actions:
  pullRequest:
    kind: github/pullrequest
    scmid: default
    title: "Actualizar NGINX Ingress Controller"
    spec:
      labels:
        - dependencies
        - networking
      description: |
        ## Actualización automática de NGINX Ingress Controller
        
        Actualizaciones:
        - Chart: Nueva versión disponible
        - Imagen: Nueva versión disponible
        
        ### Cambios notables
        
        Revisar:
        - [Changelog](https://github.com/kubernetes/ingress-nginx/tree/main/charts/ingress-nginx)
        - [Releases](https://github.com/kubernetes/ingress-nginx/releases)
        
        ### Verificación
        
        - [ ] Revisar cambios
        - [ ] Probar en ambiente de desarrollo